from typing import Protocol, Iterable, Any
from domain.models import ChatSession, UserProfile

class ChatSessionStore(Protocol):
    async def set_active(self, chat_id: int, active: bool) -> None: ...
    async def is_active(self, chat_id: int) -> bool: ...
    async def list_active(self) -> Iterable[int]: ...

class LLMClient(Protocol):
    async def reply(self, *, user_text: str, chat_id: int) -> str: ...
    async def reply_with_image(
        self,
        *,
        chat_id: int,
        image_bytes: bytes,
        image_mime_type: str,
        user_text: str = "",
    ) -> str: ...

class NutritionLogStore(Protocol):
    async def add_items(self, chat_id: int, items: list[dict[str, Any]]) -> None: ...
    async def get_log(self, chat_id: int) -> list[dict[str, Any]]: ...
    async def clear(self, chat_id: int) -> None: ...
    async def remove_last(self, chat_id: int) -> bool:  ...

class UserProfileStore(Protocol):
    async def get(self, chat_id: int) -> UserProfile | None: ...
    async def upsert(self, profile: UserProfile) -> None: ...
    async def ensure(self, *, chat_id: int, name: str | None, username: str | None) -> tuple[UserProfile, bool]: ...
    async def extend_subscription(self, chat_id: int, days: int) -> str: ...
    async def increment_referals(self, chat_id: int, by: int = 1) -> None: ...
    async def add_referral_username(self, chat_id: int, referred_username: str | None) -> None: ...
    async def set_calories_goal(self, chat_id: int, goal: int | None) -> None: ...
